language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

dist: trusty

before_script:
  - composer self-update && composer install --no-interaction

script: vendor/bin/phpunit --configuration phpunit.xml

notifications:
  email: false
